### ISSUE TITLE
Cannot read property 'accessKeyId' of null

### ISSUE THREAD

**Issue by JanikBuecher** [IBM-Cloud/code-engine-text-analysis#3]
When trying to set up the tutorial I get this backend error. Apparently, I am doing something wrong with my setup with cos.
Could you maybe provide a video or a more thorough tutorial with photos where to click?

**Comment by JanikBuecher** [comment]
**Issue solved**: When binding credentials, like 'i_bmcloud code-engine application bind --name backend --service-instance code-engine-cos --service-credential cos-for-code-engine --prefix COS_' use ..._SECRET at the end of prefix.
-> '_ibmcloud code-engine application bind --name backend --service-instance code-engine-cos --service-credential cos-for-code-engine --prefix COS_SECRET_'

**Reason**: COS changed API Version to v2, causing the keys to loose the _SECRET part of their name

**Comment by VidyasagarMSC** [comment]
Issue resolved over a call.
