### ISSUE TITLE
Make /items and /analyzetext return JSON that can be used by a tool like jq

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/code-engine-text-analysis#5]
Calling these endpoints result in a JSON output that has a "data" attribute and a value that is another JSON with some data being encoded.

Is the encoded data the actual file content? We don't really need this to show up in the UI, only the title, the size and maybe the first X characters of the text should be enough.

What are these encoded data? and why not returning plain JSON that I can pass directly to jq?

**Comment by VidyasagarMSC** [comment]
Each item returned by the COS SDK is in the below format

```
{
  AcceptRanges: 'bytes',
  LastModified: 'Mon, 01 Feb 2021 09:30:37 GMT',
  ContentLength: '548322',
  ETag: '"fab2398e53e19d9483252dda6ccccxxx"',
  ContentType: 'application/octet-stream',
  Metadata: { fieldname: 'files' },
  Body: <Buffer xxxxx ... 548272 more bytes>
}
```
So, we are reading the Buffer body of each item,  converting the `Body` into `BASE64` string and adding it to a Javascript dictionary for being decoded on the client side using `atob` method.
