### ISSUE TITLE
NLU language identification 

### ISSUE THREAD

**Issue by alejandrobohorquez96** [IBM-Cloud/code-engine-text-analysis#6]
The job does not specified the language in which the text will be provided for the user through the UI, resulting in a "Bad Request: unsupported text language: unknown". I could fix it adding the 'language':'en' in the analyzeParams of the getItem function. However, this prevents the tutorial to be practicable for a non English text file.

**Comment by VidyasagarMSC** [comment]
The code changes are in-place and the respective container images are updated and pushed.

@alejandrobohorquez96 Can you check and close the issue?

**Comment by alejandrobohorquez96** [comment]
Thanks Vidyasagar I check the changes and now it is working.
